[package]
name = 'OverflowingMath'
version = '0.2.0'
upgrade_policy = "immutable"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "f18cc2cac521b2a2eae5a5f08f1b787f61a2279d"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { std = "0x1" }

[addresses]
overflowing_math = "0x4e9fce03284c0ce0b86c88dd5a46f050cad2f4f33c4cdd29d98f501868558c81"